PAYONE-GmbH/magento-2

- Helper/Api.php
- Helper/Base.php
- Helper/Checkout.php
- Helper/ConfigExport.php
- Helper/Country.php
- Helper/Customer.php
- Helper/Database.php
- Helper/HostedIframe.php
- Helper/Order.php
- Helper/Request.php
- Helper/Shop.php
- Helper/Toolkit.php
- Model/PayoneConfig.php
- Observer/AddPaypalExpressButtons.php
- README.md
- composer.json
- etc/adminhtml/system.xml
- etc/adminhtml/system/payone_obt_sofortueberweisung.xml
- etc/config.xml
- etc/module.xml
- i18n/de_DE.csv
- i18n/en_US.csv
> Fixed DI errors

- Block/Adminhtml/Information.php
- Model/Methods/BaseMethod.php
Added partial capture and refund. Fixes #15
> Partial Capture and Refund

- view/frontend/web/js/view/payment/method-renderer/base.js
- view/frontend/web/js/view/payment/method-renderer/creditcard-method.js
> Fixed the creditcard validation problem.

- Api/AddresscheckInterface.php
- Service/Addresscheck.php
- Service/V1/Addresscheck.php
- etc/di.xml
- etc/webapi.xml
> MAG2-11 - Fixed the changes of davidverholen to the addresscheck api implementation

- .idea/composerJson.xml
> Remove .idea directory

- Block/RedirectReturn.php
- Controller/Onepage/Cancel.php
- Controller/Onepage/Returned.php
- Observer/PredispatchCheckoutIndex.php
- etc/events.xml
- view/frontend/layout/checkout_index_index.xml
- view/frontend/templates/redirect_return.phtml
Fixes #25
After some trying around I went with a different approach
> MAG2-10 - Fixed brower back button problem

- Block/Adminhtml/Config/Form/Field/CreditcardTemplate.php
> Fixed escaping problem in cc_template

- Model/Api/Request/Base.php
- Model/Methods/PayoneMethod.php
- Test/Unit/Model/Api/InvoiceTest.php
- Test/Unit/Model/Api/Request/AddresscheckTest.php
- Test/Unit/Model/Api/Request/AuthorizationTest.php
- Test/Unit/Model/Api/Request/CaptureTest.php
- Test/Unit/Model/Api/Request/ConsumerscoreTest.php
- Test/Unit/Model/Api/Request/DebitTest.php
- Test/Unit/Model/Api/Request/Genericpayment/PayPalExpressTest.php
- Test/Unit/Model/Api/Request/GetfileTest.php
- Test/Unit/Model/Api/Request/ManagemandateTest.php
- Test/Unit/Model/Api/Request/UpdateuserTest.php
- Test/Unit/Model/Methods/BaseMethodTest.php
- Test/Unit/Model/Methods/InvoiceTest.php
- Test/Unit/Model/Methods/OnlineBankTransfer/SofortUeberweisungTest.php
- Test/Unit/Model/Methods/PayoneMethodTest.php
- Test/Unit/Model/Methods/PaypalTest.php
All testable classes now have unittests
> MAG2-2 Final checkin of the unit tests

- Model/Api/Request/Consumerscore.php
> MAG2-33 - Fixed the php notice message

- etc/config.xml
> MAG2-36 - No default value for request type

- etc/module.xml
> Add Module sequence in module.xml to enable integration tests

- view/frontend/web/js/view/payment/method-renderer/creditcard-method.js
- view/frontend/web/js/view/payment/method-renderer/debit-method.js
- view/frontend/web/js/view/payment/method-renderer/payolution_installment-method.js
> MAG2-37 - Fixed problems with minified Javascript function

- Model/PayoneConfig.php
- etc/module.xml
> Version bump to 1.3.6

- composer.json
Otherwise this extension cannot be used with magento 2.2.0
> update composer.json to accept magento 2.2.0

- i18n/de_DE.csv
> Add missing CC translations

- .travis.yml
- composer.json
> PHP 7.1 compat

- Setup/UpgradeSchema.php
> MAG2-43 - Added checkout connection name to UpgradeSchema

- Helper/Environment.php
- Model/Environment/RemoteAddress.php
- Test/Unit/Helper/EnvironmentTest.php
- Test/Unit/Model/Environment/RemoteAddressTest.php
- etc/adminhtml/system.xml
- etc/config.xml
> MAG2-59 - Added proxy mode to TransactionStatus script

- Api/Data/EditAddressResponseInterface.php
- Api/EditAddressInterface.php
- Service/V1/Data/EditAddressResponse.php
- Service/V1/EditAddress.php
- Test/Unit/Service/V1/Data/EditAddressResponseTest.php
- Test/Unit/Service/V1/EditAddressTest.php
- etc/di.xml
- etc/webapi.xml
- view/frontend/web/js/action/edit-address.js
- view/frontend/web/js/view/shipping-mixin.js
> MAG2-67 - Addresscheck will now also be executed for existing addresses

- Block/Onepage/Review.php
- Helper/Base.php
- Helper/Consumerscore.php
- Helper/Database.php
- Test/Unit/Helper/ApiTest.php
- Test/Unit/Helper/BaseTest.php
- Test/Unit/Helper/ConfigExportTest.php
- Test/Unit/Helper/ConfigTest.php
- Test/Unit/Helper/ConsumerscoreTest.php
- Test/Unit/Helper/CountryTest.php
- Test/Unit/Helper/EnvironmentTest.php
- Test/Unit/Helper/HostedIframeTest.php
- Test/Unit/Helper/PaymentTest.php
- Test/Unit/Helper/RequestTest.php
- Test/Unit/Helper/ShopTest.php
- Test/Unit/Helper/ToolkitTest.php
> MAG2-96 Crash when removing stores

- Controller/ExternalAction.php
- Controller/Onepage/Returned.php
- Controller/Transactionstatus/Index.php
> MAG2-112 - Fixed problems with Magento 2.3.2 Csrf changes

- Helper/Addresscheck.php
- Model/Api/Request/Addresscheck.php
- Model/Plugins/BillingAddressManagement.php
- Model/Plugins/ShippingAddressManagement.php
- Model/Risk/Addresscheck.php
- Test/Unit/Helper/AddresscheckTest.php
- Test/Unit/Model/Api/Request/AddresscheckTest.php
- Test/Unit/Model/Plugins/BillingAddressManagementTest.php
- Test/Unit/Model/Plugins/ShippingAddressManagementTest.php
- Test/Unit/Model/Risk/AddresscheckTest.php
- Test/Unit/Model/TransactionStatus/ForwardingTest.php
> MAG2-111 - Improved the performance behaviour of the addresscheck

- Model/Plugins/State.php
- Test/Unit/Model/Plugins/StateTest.php
- etc/di.xml
> MAG2-122 - Fixed Mage2-Core bug with wrong order status

- Model/Methods/PayoneMethod.php
- Test/Unit/Model/Methods/CreditcardTest.php
> MAG2-129 - Fixed store-awareness problems

- Model/Plugins/State.php
- Test/Unit/Model/Plugins/StateTest.php
> MAG2-122 - Added new solution for virtual orders status mapping problem

- view/frontend/web/js/view/payment/method-renderer/payolution_installment-method.js
> MAG2-131 Removed deprecated prototypeJS dependency

- Controller/Transactionstatus/Decouple.php
> MAG2-151 - Fixed transaction status compatibility

- etc/adminhtml/system/payone_klarna_base.xml
> MAG2-161 - Added active control for Klarna Base method

- .github/workflows/build_magento23.yml
Move Magento 2.3 build to Github Actions
> Noticket: Build with Magento 2.3

- Model/Api/Invoice.php
> #344 change handling of gift-card-amount

- Observer/Transactionstatus/Paid.php
- etc/adminhtml/system/payone_advance_payment.xml
- etc/config.xml
> #348 make creating invoice configurable

- Model/Api/Invoice.php
> MAG2-189 - Fixed problem with invoice item SKU

- Model/PayoneConfig.php
New Features
Add Apple Pay
Add mechanism to prevent double invoice creation
Add creditcard cardholder field
Add country restrictions for Boniversum addresscheck
Bugfixes
Fixed faulty JSON
Fixed class name of Unit Test
Fixed problem with hardcoded dummy birthday
Fixed gift card amount increase discount diff
Maintenance
Add Unit Tests
> version bump to 330

- composer.json
- etc/module.xml
Fixed version number in module.xml
> MAG2-217 - Readded version number to composer.json

- Model/PayoneConfig.php
- etc/module.xml
New Features
- Bancontact integrated
Bugfix(es)
- Fixed problem with Klarna for registered users
- Do not cancel successful paid redirect payments even after interruption
- Amazon Pay fix: Load quote only when checkoutConfig is available
Maintenance
- Readded version number to composer.json
- Changed internal payment names
- Added CSP whitelist to module
- Removed accountnumber and bank code from invoice
- tested with 2.4.3
> version bump to 340

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
New Features
- Bancontact integrated
Bugfix(es)
- Fixed problem with Klarna for registered users
- Do not cancel successful paid redirect payments even after interruption
- Amazon Pay fix: Load quote only when checkoutConfig is available
Maintenance
- Readded version number to composer.json
- Changed internal payment names
- Added CSP whitelist to module
- Removed accountnumber and bank code from invoice
- tested with 2.4.3
- Change of composer.json
> version bump to 341

- view/frontend/web/js/view/payment/method-renderer/base.js
- view/frontend/web/js/view/payment/method-renderer/payolution_debit-method.js
- view/frontend/web/js/view/payment/method-renderer/payolution_installment-method.js
- view/frontend/web/js/view/payment/method-renderer/payolution_invoice-method.js
- view/frontend/web/js/view/payment/method-renderer/ratepay_invoice-method.js
> add validation if birthday is a valid date

- view/frontend/templates/onepage/amazon.phtml
> MAG2-242 - Fixed issue with Amazon Pay Widget javascript

- view/frontend/templates/redirect_return.phtml
> MAG2-255 - Fixed problem with compatibility to Amasty Checkout

- Helper/AmastyGiftcard.php
> MAG2-260 - Added missing parameter

- Helper/Customer.php
> MAG2-266 - Fixed faulty state codes

- .github/workflows/build_magento246php82.yml
- Controller/Amazon/LoadReview.php
- Model/Api/Payolution/PrivacyDeclaration.php
- Model/Entities/ApiLog.php
- Model/Entities/TransactionStatus.php
- Model/Methods/OnlineBankTransfer/Ideal.php
- Model/ResourceModel/TransactionStatus.php
- Observer/PaymentSystemConfigChanged.php
- Test/Unit/Block/Adminhtml/Config/Form/Field/LabelTest.php
- Test/Unit/Block/RatepayDeviceFingerprintTest.php
- Test/Unit/Helper/ToolkitTest.php
- Test/Unit/Model/Entities/ApiLogTest.php
- Test/Unit/Model/Entities/TransactionStatusTest.php
> MAG2-290 - Added compatibility to Magento 2.4.6 and PHP 8.2

- Controller/Onepage/PlaceOrder.php
- Controller/Paydirekt/Agreement.php
- Controller/Paypal/Express.php
- Helper/Checkout.php
- Test/Unit/Controller/Onepage/PlaceOrderTest.php
- Test/Unit/Helper/CheckoutTest.php
> MAG2-291 - Fixed problem with different tax rate in PayPal Express

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
Bugfixes
* fixed problem with Swissup Firecheckout Thanks @pointia
* fixed birthday field for secure invoice
* fixed problem with ratepay device fingerprint
Maintenance
* updated the iDEAL issuer list
* updated the hash method
* removed paydirekt and updated giropay
tested with 2.4.6
> Version bump 3102

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
Maintenance
* compatible with 2.4.7
* tested with 2.4.7
> version bump to 3110

- Block/RedirectReturn.php
- view/frontend/templates/redirect_return.phtml
> MAG2-311 - Added fix for inline javascript problem in Mage 2.4.7

- Helper/Environment.php
> MAG2-318 - Fixed client ip getter

- Helper/Toolkit.php
- Test/Unit/Helper/RatepayTest.php
> MAG2-324 - Fixed a problem with hash function

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
New Features
* New payment method: PayPal v2
Bugfix
* Fixed problems with birthdate validation and usage in safe invoice payment method
Maintenance
* Added an info in the backend concerning substitute orders
* tested with 2.4.7
> version bump to 3130

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
New Features
* New payment method: PayPal v2
Bugfix
* Fixed problems with birthdate validation and usage in safe invoice payment method
* Changed SDK URL parameter
Maintenance
* Added an info in the backend concerning substitute orders
* tested with 2.4.7
> version bump to 3.13.1

- view/frontend/web/js/model/error-processor-mixin.js
> MAG2-331 - Converted error processor fix

- Model/Methods/AmazonPayV2.php
- etc/config.xml
> MAG2-336 - Fixed config problem with AmazonPayV2

- view/frontend/web/template/payment/amazonpayv2.html
- view/frontend/web/template/payment/bnpl_debit.html
- view/frontend/web/template/payment/bnpl_installment.html
- view/frontend/web/template/payment/bnpl_invoice.html
- view/frontend/web/template/payment/creditcard.html
- view/frontend/web/template/payment/debit.html
- view/frontend/web/template/payment/payolution_debit.html
- view/frontend/web/template/payment/payolution_installment.html
- view/frontend/web/template/payment/payolution_invoice.html
- view/frontend/web/template/payment/ratepay_debit.html
- view/frontend/web/template/payment/ratepay_installment.html
- view/frontend/web/template/payment/ratepay_invoice.html
- view/frontend/web/template/payment/safe_invoice.html
> MAG2-338 - Added missing quotes for autocomplete attribute

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
Bugfix
* Added security mechanism to express checkouts
Maintenance
* tested with 2.4.7
> version bump to 3141

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
Bugfix
* Added config option for Google Pay merchantid
Maintenance
* tested with 2.4.8
> version bump to 3142
