- Block/Adminhtml/Information.php
admin/payone/information fails on https sites due to hardcoded protocol
> http(s) for admin/payone/information

- view/frontend/web/js/view/payment/method-renderer/creditcard-method.js
Wenn ich als Kunde eine Bestellung per Kreditkarte durchführen möchte, aber vergessen habe, das Verfallsdatum einzugeben, wird keine Fehlermeldung angezeigt.
Stattdessen wird nur eine Ausgabe in der Browser-Konsole ausgegeben:
`console.debug("not complete");`
In diesem Patch wird dies ersetzt durch eine Magento-Fehlermeldung
> Kreditkartenzahlung: Fehlermeldung wenn kein Verfallsdatum eingegeben wurde.

- Observer/Transactionstatus/Paid.php
Forwarding server throws an error if order does not exist and cannot return "TSOK".
> new event payone_core_transactionstatus_paid breaks transaction status forwarding

- Helper/Environment.php
1. To use transaction forwarding you have to add the IP address of the forwarding server to the "Valid PAYONE IPs" configuration setting. Although it's quite obvious once you know it, it took me a while to figure this out, so adding a little hint in the configs's description would be helpful.
2. When I added a third IP address it stopped working for the second IP address. Dumping $aWhitelist in Helper\Environment.php line 64 shows that it's due to linebreaks from the textarea
array(3) {
[0]=>
string(12) "185.60.20.*
"
[1]=>
string(11) "173.194.219.94
"
[2]=>
string(9) "127.0.0.1"
}
Works only for the last IP address or if the IP address contains a wildcard.
> fix transaction status forwarding with multiple IPs

- Helper/Toolkit.php
- Model/Api/Request/Authorization.php
- Model/Api/Request/Capture.php
- Model/Api/Request/Debit.php
- Model/Api/Request/Genericpayment/PreCheck.php
- Model/Source/Currency.php
- etc/adminhtml/system.xml
- i18n/de_DE.csv
Fixes #157 
- added config field to chose currency for transmission (base or default display currency)
- added two methods in Payone\Core\Helper\Toolkit:
- **convertToTransmitCurrency($amount)** converts from base (order) currency to configured currency
- **getTransmitCurrencyCode()** returns the corresponding currency code
- added usage of said methods to Capture, Authorization, Debit, and Precheck requests
I hope this helps fix the problem quickly. I chose the toolkit helper since it already seems to be a kind of general purpose helper. If the placement is wrong for any reason, just change it, or tell me and I will. There might be more classes that need to convert an amount, but those four were the most obvious to me.
> Fix for #157: wrong currency transmitted

- Observer/Transactionstatus/Paid.php
In the observer that handles the "paid" transactionstatus, the $oInvoice object can be null, in which case the observer fails without notice. I'd recommend adding logging to the oberser(s), too, as it simplifies debugging.
> only try to save invoice, if it exists

- Observer/Transactionstatus/Appointed.php
During the handling of a support case I noticed a "GoMage OrderEmail" module on a server of a customer, which overrides Payone functionality so that the order-email is sent instantly when the order is created.
The Payone module intentionally disables the transmission of the order email in the moment when the order is created and instead sends it when the APPOINTED status arrives, because only then the payment was accepted.
In the case of the customer with the GoMage module the processing of the APPOINTED status is canceled and therefore no invoice is created, which will lead to problems in the PAID status processing, because there is no invoice available to mark as paid.
With this patch the order-email transmission logic may be wrong for customers using this kind of module but at least …
> Not cancelling APPOINTED processing anymore when email was already sent

- Setup/UpgradeSchema.php
- etc/module.xml
- Transaction status messages identify the according order by the txid. The column had no index
and therefore those requests may have consumed some time when a lot of transactions are held in
this table.
- Remove wrong duplicated comment
In our scenario the order lookup in transaction status processing could be reduced from 1.4 to 1.7 seconds (no query_cache) to 200ms to 300ms.
*Repro*
1. Run `bin/magento setup:upgrade`
1. check structure of table `payone_protocol_api`
1. An index `PAYONE_PROTOCOL_API_TXID` exists
> speed up api calls for transaction status messages

- Setup/UpgradeSchema.php
If a table prefix is used, the setup process crashes.
> Current Version crashes setup:upgrade

- Setup/UpgradeSchema.php
- etc/module.xml
This fixes an issue if account ID or portal ID is greater than 65535.
It is stored correctly in payone_protocol_api as integer but in payone_protocol_transactionstatus it is stored as smallint.
> Fix account ID and portal ID are stored as smallint in transactionstatus table

- Helper/Api.php
We sometimes see exceptions when the status is missing in the API response. This is also mentioned in #148 
I would assume if the status is missing we set it to "ERROR". The following code then requires the keys  "errorcode" and "customermessage" set in Model/Methods/PayoneMethod.php line 151
https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Methods/PayoneMethod.php#L151
> Fix missing status in response in case of curl timeouts. Fixes #148

- Observer/AddAmazonPayButton.php
If you have the AmazonPay Module enabled and navigate to 
magento2-checkout in magento2-ee version 2.1.17, there are 2 events fired
to the observer. This results to the AmazonPay Button not being
rendered in the Checkout. By ignoring the 'map.shortcut.buttons'
fired by module-msrp, the AmazonPayButton is being rendered correctly
> Extend array for AmazonPayButton Observer

- etc/webrestrictions.xml
This is change is necessary if website-restrictions are enabled (Magento Enterprise feature).
Without it calls to the transactionstatus-controller would be redirected to customer-login and none of the orders' status would be updated.
> added webrestrictions.xml to avoid transaction-updates being blocked

- view/frontend/web/js/view/payment/method-renderer/payolution_installment-method.js
In case Payolution Invoice method is disabled in your M2 project, you'll get "false" returned as a content of getPrivacyDeclaration() method after you click "acceptance" link on the storefront. Backend prepared separate privacy declaration for each of payolution methods but only invoice is used for all payolution payment methods, which seems to be a bug to me. After proposed changes everything looks good
> Fixes path to privacyDeclaration for Installment

- view/frontend/web/js/view/payment/method-renderer/payolution_debit-method.js
In case Payolution Invoice method is disabled in your M2 project, you'll get "false" returned as a content of getPrivacyDeclaration() method after you click "acceptance" link on the storefront. Backend prepared separate privacy declaration for each of payolution methods but only invoice is used for all payolution payment methods, which seems to be a bug to me. After proposed changes everything looks good
> Fixes path to privacyDeclaration for Debit method

- Model/TransactionStatus/Forwarding.php
Fixes #316 
This is the "quick and dirty" variant of a fix for the mentioned issue.
It would be nicer to have a real async forwarding process, making use either of a cron job (bad memories from Magento 1), or RabbitMQ if available.
> Noticket: Increase TX-Status forwarding timeout

- Model/Api/Invoice.php
- Test/Unit/Model/Api/InvoiceTest.php
When gift card and cart price rule is enabled, the gift card amount is counted twice.
In the function `addDiscountItem` the diff between order amount and quote amount with discount is calculated before gift card is added.
This `diff` has value of gift card and increase the discount amount.
There is the code responsible for adding the gift card amount to the discount.
// The calculations broken down to single items of Magento2 are unprecise and the Payone API will send an error if
// the calculated positions don't match, so we compensate for rounding-problems here
https://github.com/PAYONE-GmbH/magento-2/blob/master/Model/Api/Invoice.php#L277
> Gift card is counted twice when discount form cart price rule is enabled

- Block/Info/Creditcard.php
*Reason for the change*
During the changes in https://github.com/PAYONE-GmbH/magento-2/commit/342404b808c772145ab3465daa3131ac2144cab7#diff-57bbdd480bb30e81d51d4183f83e3b47c0347f0658a1793e054f3739c44ef065 the structure of the array was changed, but the implementation of getCreditcardType does not represent those changes up to now.
As the Payone-Server still returns the 1-letter code of the creditcard-type (e.g. 'V' for Visa) the current implementation finds no entry in the array and returns an empty string.
This results in an empty creditcard-type entry in the order-details of the Magento backend and order confirmation e-mails.
*Steps to verify the change*
- Place an order with payment-method creditcard, wait for appointed-call to arrive
- Check order details in Magento backend and …
> MAG2-184: Fix for empty creditcard-type in Info-block

- view/frontend/web/js/model/error-processor-mixin.js
I have installed [Amazon Pay extension](https://github.com/amzn/amazon-payments-magento-2-plugin) which uses error processor in [amazon-button.js ](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/master/view/frontend/web/js/amazon-button.js) which is loaded in minicart (and thus on every page).
As PAYONE extension applies mixin for error-processor, it requires static files from Checkout such as method list and quote. So whenever amazon-button loads, for example on PDP, quote tries to execute `quoteData = window.checkoutConfig.quoteData,` which returns in error because window.checkoutConfig is not available for PDP. There is no such error in Cart or Checkout.
It would be the best if any other extension using error processor could use original file without mixin, and the mixin …
> fix: Load quote only when checkoutConfig is available

- view/frontend/web/js/view/payment/method-renderer/creditcard-method.js
This fixes https://github.com/PAYONE-GmbH/magento-2/issues/428
If the user has no saved cards, getSelectedSavedCardPan() will return undefined, causing the condition in line 71 to become true.
getSelectedCardholder() will return false if the user has no saved card selected, overwriting the actual cardholder value from the form with an incorrect value.
I've fixed this by including a check for useSaveDataMode(), which returns false if user has no saved cards yet.
> Fix creditcard cardholder is not saved on first entry

- view/frontend/web/js/view/payment/method-renderer/creditcard-method.js
A customer complained about not being able to enter his academic title ("Dr.") in the credit card holder field. This change enables customers to enter "." in the credit card holder field.
> allow academic title in credit card holder name

- Model/Plugins/MethodList.php
A customer has brought to our attention that the payment method Klarna no longer appears.
After debugging, I found the error. 
**\Payone\Core\Model\Plugins\MethodList::checkKlarnaMethods**
The error is in the for loop. 
In case of a certain order of the payment methods, an unset is set to the wrong key and the Klarna payment methods do not appear anymore. 
The error occurs only when Klarna is in the last position as payment method (klarna base and **only one** of the klarna payment methods).
**Steps to reproduce**
1. Enable multiple payment methods in Payone (Klarna Base included)
2. activate only one Klarna payment method (one of Klarna "Pay Later", Klarna "Pay Now" or Klarna "Slice It")
3. klarna should be the last activated payment method, please do not activate any payment methods …
> klarna base removed by false array key

- Model/TransactionStatus/Forwarding.php
If a server is not properly configured, specific internal routes, such as `"payone/transactionstatus/decouple"`, could be relocated due to `"301 Moved Permanently"` status. In this case, the POST request in forwardAsyncRequest fails to operate as expected. This impacts for example the TransactionStatus Forwarding mechanism, as the request doesn't follow through the redirect and no further functions are called.
This issue became evident after the implementation of varnish cache on our server. Our server had a flaw where the calls to `"payone/transactionstatus/decouple"` weren't whitelisted directly (301 moved permanently), thereby inhibiting the TransactionStatus from being correctly forwarded. This issue was harder to narrow down due to a lack of logging.
In order to avoid this behavior i …
> forwardAsyncRequest: Follow 301 Redirects to the End Location

- Model/PayoneConfig.php
- composer.json
- etc/module.xml
New Features
* Klarna B2B invoice now used the Billie widget
* Added compatibility to Magento 2.4.6 and PHP 8.2
* Implement B2B payments for BNPL Secured Invoice
Bugfixes
* Fixed problem with different tax rate in PayPal Express
* Update de_DE.csv for correct umlaut display - Thanks to @splendidinternet
* Update Forwarding.php - Thanks to @nicolasbachmaier
Maintenance
* Hide Klarna debit and installment for B2B orders
* Tested with 2.4.6
> version bump to 390

- view/frontend/web/js/view/billing-address-mixin.js
This might happen when you use a 1 step checkout e.g. Swissup Firecheckout or so
> Fix if paymentMethod is empty

- view/adminhtml/ui_component/payone_protocol_api_grid.xml
- view/adminhtml/ui_component/payone_protocol_transactionstatus_grid.xml
Fixes #578
Fix the XML error 'Element 'indexField': This element is not expected' in the admin panel route `payone/protocol_transactionstatus/index`.
* Remove the `<indexField>id</indexField>` element from the `<column name="id">` section in `view/adminhtml/ui_component/payone_protocol_transactionstatus_grid.xml`.
* Remove the `<indexField>id</indexField>` element from the `<column name="id">` section in `view/adminhtml/ui_component/payone_protocol_api_grid.xml`.
> Fix XML error in admin panel route
